file_dir: /nesi/nobackup/uoo03104/Taylor200_coldglac_2122_aws_newalb_Dec/NWM
save_dir: /nesi/nobackup/uoo03104/Taylor200_coldglac_2122_aws_newalb_Dec/NWM
station_names: cwg
plot_names: [heatflux, tsfc, albdiognosis, precip, albedo, snowheight, massbal, energybal, icetD, icetH, flow, 4panel, xsect_top2, xsect_top, melt]
date: 2021-12-18\ 00:00:00
